USE [CARRERA]
 QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[fn_porcentaje_carrera](@ID_ALUMNO int) 
returns numeric(5,2)
as begin

	DECLARE @TOTAL_MATERIAS INT
	DECLARE @TOTAL_APROBADAS INT
	DECLARE @RETORNO NUMERIC(5,2) = 0

	SELECT @TOTAL_MATERIAS= COUNT(*) FROM MATERIA

	IF  @TOTAL_MATERIAS > 0 BEGIN

		SELECT @TOTAL_APROBADAS = COUNT(*) FROM FINALES F
		WHERE 
			F.ID_ALUMNO = @ID_ALUMNO
			AND F.NOTA >=4
		
		SET @RETORNO = CAST(@TOTAL_APROBADAS AS numeric(5,2)) * 100 / @TOTAL_MATERIAS
	END

	
	RETURN @RETORNO



end

GO

